### ISSUE TITLE
Enemy re-spawn overload

### ISSUE THREAD

**Issue by rhys-the-davies** [wimpysworld/little-spy#1]
Great game, good fun, very easy to get stuck in. However, when I kill a bad guy and they're supposed to come back, it doesn't reset when the level restarts. So I kill a bunch of baddies, but then I die and go to do the level again and shit goes off. I recorded this just before it crashed my browser: 

https://user-images.githubusercontent.com/56505487/125198414-a8fc3600-e259-11eb-8014-26a407848717.mp4

If you fix that, I'd suggest adding something like 5 or 10 enemy kills and you get a life back. I'm a gamer who has to collect everything so I will not progress until I do. And with floods of enemies like this, it quickly becomes a death spiral 🤣

**Comment by flexiondotorg** [comment]
Thanks for the bug report :+1: Fix via https://github.com/wimpysworld/little-spy/commit/77515062aa385c5612f925660f974be426daf9ca and available in v1.0.4 of the game 🙂
